### PR TITLE
Added Python 3 support

### PR DESCRIPTION
**Pull request by ZuluPro**
Added Python 3 support,
And fixed some PEP8.

### CODE REVIEW

**Comment by EfrenRey** [comment]
Hi @ZuluPro, thank you very much to collaborate with this library.
Changes looks very good. We still have to do some regression tests, to verify everything is working as expected, before merge the changes.
Thanks.

**Comment by ZuluPro** [comment]
@EfrenRey Any news ?

**Comment by ZuluPro** [comment]
Any news ?

**Comment by EfrenRey** [comment]
@ZuluPro Sorry for the delay. Thanks for collaborate.

**Pull request merged**
